// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WaldeningApi.Models;

#nullable disable

namespace WaldeningApi.Migrations
{
    [DbContext(typeof(WaldeningApiContext))]
    [Migration("20231125063226_Paging")]
    partial class Paging
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("WaldeningApi.Models.Park", b =>
                {
                    b.Property<int>("ParkId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Activities")
                        .HasColumnType("longtext");

                    b.Property<bool>("IsNational")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<string>("State")
                        .HasColumnType("longtext");

                    b.Property<string>("Website")
                        .HasColumnType("longtext");

                    b.HasKey("ParkId");

                    b.ToTable("Parks");

                    b.HasData(
                        new
                        {
                            ParkId = 1,
                            Activities = "Biking,Hiking,Camping,Swimming,Rock Climbing",
                            IsNational = false,
                            Name = "McKinley Falls State Park",
                            State = "Texas",
                            Website = "https://tpwd.texas.gov/state-parks/mckinney-falls"
                        },
                        new
                        {
                            ParkId = 2,
                            Activities = "Hiking,Canyoneering,Camping,Swimming,Spelunking,Rock Climbing",
                            IsNational = true,
                            Name = "Grand Canyon National Park",
                            State = "Arizona",
                            Website = "https://www.nationalparks.org/explore/parks/grand-canyon-national-park"
                        },
                        new
                        {
                            ParkId = 3,
                            Activities = "Hiking,Camping,Swimming",
                            IsNational = false,
                            Name = "Pedernales Falls State Park",
                            State = "Texas",
                            Website = "https://tpwd.texas.gov/state-parks/pedernales-falls"
                        },
                        new
                        {
                            ParkId = 4,
                            Activities = "Dune Sledding,Hiking,Cabin Rental,Biking",
                            IsNational = true,
                            Name = "White Sands National Park",
                            State = "New Mexico",
                            Website = "https://www.nps.gov/whsa/index.htm"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
